### ISSUE TITLE
Login causes graph to shift

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#171]
From #169: 
> an old issue that when you login, the graph gets shifted up and two the left for some reason

**Comment by benloh** [comment]
@jdanish Logging in actually causes a complete page reload.  The redraw is probably what is causing the graph to look like it's shifted (I think)?  Any chance you can show me a dataset or a movie cliip of this happening?

**Comment by jdanish** [comment]
Sorry, it is apparently only for the graphs where you cannot display it without a login. Once you login it displays as if the center is up and to the left of the screen rather than the actual center. I can take a pic later if that doesn't make it easy to reproduce.

**Comment by benloh** [comment]
Ah!  I see now, thanks.

**Comment by benloh** [comment]
# The Problem

We were using React's "hidden" attribute to hide the graph if the user was not logged in.  The problem is that if the graph is hidden, its size is never correctly calculated -- it ends up with a width and height of 0.  So when the graph is eventually loaded and zoomed, it does so assuming the graph is 0x0.

# The Solution

Using CSS `visibility: hidden` fixes the problem -- it allows the browser to create objects and properly calculate heights.

Should be fixed with : 2bb2ac51fd159e6d4af0ff5b082eca2068297238

**Comment by jdanish** [comment]
Looks fixed. Awesome. Thanks!
