### ISSUE TITLE
Newest build doesn't work with package command

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#185]
If you use npm run package, the output isn't loading a network. See attached for console errors
<img width="1816" alt="Screen Shot 2021-12-18 at 8 25 54 AM" src="https://user-images.githubusercontent.com/5529898/146642702-b60af3b8-5970-4a61-9a42-4151bf69131b.png">
.

**Comment by jdanish** [comment]
@kalanicraig as an FYI since we talked about testing this.

**Comment by benloh** [comment]
@jdanish two questions:
1. Did you specify a dataset in the URL?  e.g. `http://ben.netcreate.org:8888/?dataset=Grimm#/`
2. Is the dataset readonly?  This is the screen you'll see if it's readonly.

I believe we currently do not support logging in standalone to readonly databases.  We'd probably have to add that feature.

**Comment by jdanish** [comment]
It will run the default one without the url, but apparently it was the readonly issue. I thought I had changed that, but then I re-packaged with login required off and all worked fine. Sorry / thanks! Closing.

**Comment by benloh** [comment]
@jdanish Cool.  So we don't need to add the ability to log onto standalone dbs?

**Comment by jdanish** [comment]
No - we use package to put things either intentionally public or behind a separate more secure wall. So we can live without it for now. Long term we might want to have that or automatically un-restrict on export but we can handle it for now. Thanks!
