### ISSUE TITLE
Cleaning up Citation Prompts

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#189]
@jdanish @kalanicraig As part of the import / export feature and template development, we probably need to clean up the data structures as well.  Otherwise the whole thing becomes too Rube Goldbergy.  

One specific area I want to make sure I understand is the `citationPrompts`.  This is just a field in the template that defines the string to use when citing a node or edge presumably for a paper or classroom discussion?  Is it used for anything else?

For the template, then, it probably ought to be renamed `citation` and `citation.label` and `citation.hidden`?

(`nodePrompts` was more of a historical artifact that emerged from the original template goal of simply defining the labeling for nodes.  The template has evolved into much more than simply defining prompts, so we probably want to consider changing it to something like `nodeDefinitions`).

---

One additional note here: `citationPrompts` is easily confused with Edge's `Citations`.  I wonder if we need to come up with a better disambiguation of the user-entered citation info (e.g. source of information) from the system-generated citation (e.g. bibilographic label).

**Comment by jdanish** [comment]
Hey Ben,

I am attaching a screen capture of where this is displayed if it is not hidden. But, yes, the idea is that students can then copy this into a paper in class, or similar.

I think I called it citationPrompts to mirror nodePrompts and edgePrompts, so no need to stick with that. And agreed, citation.label makes the most sense moving forward.

Joshua

**Comment by netcreateorg** [comment]
<img width="380" alt="Screen Shot 2022-01-17 at 7 01 28 PM" src="https://user-images.githubusercontent.com/46585846/149849701-ccb838a3-d759-4aa7-b202-7611f79dce9a.png">

**Comment by benloh** [comment]
Thanks!  Given the changes all around, we may end up completely revamping the template format.  The potential issue is that this might result in a major version change with backward incompatibility.  e.g. you'd have to back and fix any existing data sets and templates that you're using.  How much of an existing base of data and templates do you have?

**Comment by netcreateorg** [comment]
On my end, not that much and easily fixed if I know the new format. Kalani?

**Comment by kalanicraig** [comment]
We have lots of templates but as long as we have a clear set of guidelines
for new vs old data and templates, I’d rather we have a good set of files
and formats now that support imports than a guarantee of backward
compatibility.

**Comment by benloh** [comment]
Implemented.
