### ISSUE TITLE
citationPrompts.hidden used to override citation?

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#192]
@jdanish I'm cleaning up templates.  Do you actually use `citationPrompts.hidden` in your template definitions to actually hide the citation prompt?  e.g. you might define the citationPrompt.citation as `H213 Prokopios Network`, but then set `hidden` to true so that it isn't shown?

Or were you using the `hidden` flag just as a way to hide the citation if it's missing?

**Comment by netcreateorg** [comment]
The hidden option turns off the display of the cite button. So I don't think there is any reason to have a prompt / label and hidden set to true. Unless you want to temporarily turn it off. I suppose we could assume that if there is a prompt it should be visible but this way it is explicit. Default should be that it is hidden: true so there is no cite button.

**Comment by benloh** [comment]
@jdanish OK, so you prefer to have two separate settings?  one to set the label and one to show/hide it?

**Comment by jdanish** [comment]
For consistency, yes please.

----
(from my iPhone)

Joshua Danish
http://www.joshuadanish.com

**Comment by benloh** [comment]
Implemented.
