### ISSUE TITLE
Tokens made w ncMakeTokens command won't validate

### ISSUE THREAD

**Issue by kalanicraig** [netcreateorg/netcreate-2018#195]
Access Tokens made with ncMakeTokens in newest /dev/ branch on MacOS using Javascript console command ncMakeTokens("PROJ","ONE","SET",50) return an "invalid code" message. <img width="1165" alt="Screen Shot 2022-01-26 at 12 48 59 PM" src="https://user-images.githubusercontent.com/9748020/151218557-9e798fe9-e41f-4438-9eab-cd05e4709532.png">

**Comment by kalanicraig** [comment]
Nevermind. Figured it out.

**Comment by benloh** [comment]
@kalanicraig Should we add a token manager interface to the list of things to build?  e.g. we can add it to the More tab for admins.  Or is that minor?

**Comment by kalanicraig** [comment]
If it's possible to do quickly, yes. Not everyone will install multiplex.

**Comment by jdanish** [comment]
It’s already in the MC interface, so really the question seems to be whether we’d want it in the “more" panel for folks who are admins in the main interface?  

I’d say let’s put it on the “list” but leave it to last?

Joshua


----
Joshua A. Danish (he, him, his) (https://www.mypronouns.org/ <https://www.mypronouns.org/>)

***@***.***

http://www.joshuadanish.com

**Comment by kalanicraig** [comment]
Agree with the "last on the list"

**Comment by benloh** [comment]
If I recall, I think it's a one hour job at max.  The issue before was that we didn't really have an interface for it.  But now that we have the more tab and better admin-only restrictions it's relatively straightforward.  I'll add it to the list.
