### ISSUE TITLE
Nodes with unselected type appear black

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#202]
In the current build, the key shows that nodes without a selected type should be gray, and the box is gray in the full edit template screen, but if you create a new node and save without selecting a type it is black.

**Comment by kalanicraig** [comment]
This is likely a factor of the new template not automatically creating a
default node definition with grey hex code

**Comment by jdanish** [comment]
I do see that entry in the template, so I am guessing it is just not getting called?

**Comment by benloh** [comment]
Actually this all depends on which branch you're on. It's in flux.

If you are on `typeedit`, then the default blank selection should be hidden from the Template Editor.

One behavior that we probably still need to work out: what should happen to a type that is not currently supported?
A node with a blank type WILL appear as gray.
But a node with an unknown type (e.g. a node with a type that has been removed, such as a "Person" node, but "Person" has been removed from the Node Type Options), the color will appear black.  We don't currently have a way to designate that color.  I suppose we could use the blank color, but black is also a way to give you feedback that a Node is using the wrong type.

If you are on `toml` or `flatten`, the default blanks are still in the editor.

**Comment by jdanish** [comment]
Yeah, I like the black for "need to re-set because you hosed the type" but this is puzzling. See the attached - I set it to unselected (appears in database as "") first by not picking a type, and then by changing the type and then changing it back to the blank option in the drop-down with the same result. This is the code from prior to the most recent commit 10 minutes ago. The node in question is named "testing" in this screen capture.

<img width="1750" alt="Screen Shot 2022-02-03 at 2 03 04 PM" src="https://user-images.githubusercontent.com/5529898/152411473-c89673a0-4cbe-476a-9542-00a8c74eae07.png">

**Comment by jdanish** [comment]
Hold on -most most recent code seems to fix it. Verifying.

**Comment by jdanish** [comment]
Newest commit works as expected so closing this.

**Comment by benloh** [comment]
This actually might raise an issue: the Edit Current Template editor will let you mess with the raw Node and Edge Type options without the transition tools (modifying dataset data, adding a replacement label).  The more focused Node Type Editor and Edge Type Editor features are the ones that have the scaffolding.  We can't easily insert the fancy Node/Edge Type Option editor into the full Current Template editor.  I suppose we can just remove the type options, or note that it's a power user feature?

**Comment by jdanish** [comment]
Either way, I think some text warning that the full template editor is for power users only is a good idea since it'll be hard to read for a non-tech-y. Beyond that I defer to Kalani since it is her users that are likely to encounter this short-term.

**Comment by benloh** [comment]
Warning text added 2512b30e5c8a6fcbb3c9699b89bfcef9a5684fce
