### ISSUE TITLE
Reload needed to update colors in the "key" after template editing 

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#206]
Note in this sample, I changed "theorist" to blue from green, and the nodes in the graph changed but the key still shows green. Reloading the page fixes the display.

<img width="1264" alt="Screen Shot 2022-02-09 at 10 38 09 AM" src="https://user-images.githubusercontent.com/5529898/153235655-59d19c5b-bb28-4842-891d-451c9c257c22.png">

Not a major issue, but worth noting.

**Comment by benloh** [comment]
Fixed with d1f1288e81347277404c172f37918b0f08b758cb

**Comment by benloh** [comment]
@jdanish please confirm fix and close this issue.

**Comment by jdanish** [comment]
Confirmed.
