### ISSUE TITLE
Auto-scaling markdown images 

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#214]
Right now images inserted into notes using markdown do not scale and there is no way to scale them. If someone puts in a GIANT one it basically breaks the interface. I think it'd be easy to mod the width on the html img tag that is generated to reflect the width of the notes field on  the side bar so this doesn't make everything a big mess?  Not a huge issue, but it comes up occasionally.

**Comment by benloh** [comment]
I wasn't aware that you could insert images :).  Do you have an example of a card with an image somewhere?

**Comment by netcreateorg** [comment]
Well, it's using the markdown plugin, so they aren't inserted so much as referenced. You can see an example on the activity systems node here: http://134.209.73.52/graph/CHAT/#/

Attaching an image in case that url doesn't work later and someone wants to know what was what. 

<img width="1803" alt="Screen Shot 2022-02-28 at 2 55 06 PM" src="https://user-images.githubusercontent.com/46585846/156049818-27d0269f-f0a3-40c8-ba69-e5df27991bed.png">

So this works great, but I had to scale the image down to make it work. Ideally all images would scale as needed.

**Comment by benloh** [comment]
Fixed with #220.
