### ISSUE TITLE
Edge "size" data

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#216]
You may recall that we hacked in the ability to set the width of edge links based on the number of connections between nodes.  Currently the "size" data is treated as a runtime-only data that is calculated when data is initially loaded and when an edge is added.

@jdanish @kalanicraig Do you think "size" should be exported with the edge data?  Importable as well?  Or should it remain a runtime-only calculation?

Either way, we need to do some re-architecting when handling importing data.

**Comment by jdanish** [comment]
I suspect that we’ll eventually want to be able to set size for a given line as more than 1?  I’ll defer to Kalani though.

**Comment by benloh** [comment]
Are you saying that you would want to set the size of the line directly and not have it calculated based on the number of edges between two nodes?  That would be two different meanings/uses of size?

**Comment by jdanish** [comment]
Well, my understanding is that in Gephi and other tools, an edge can have its own weight, and then the line weight is tied to the sum of those. 
So we *might* want to support that in the future. Kalani can confirm, though?

**Comment by benloh** [comment]
Ah.  That sounds like something to consider for the future, e.g. whether we want to add `weight` as a built-in property.  For now, I think the main question is whether we add it to the template schema so that it can be exported and imported as part of the database.

**Comment by netcreateorg** [comment]
Ahh, though if someone edited a file and made something different it'd muck with the whole calculated-on-the-fly framework, right?  In which case I'd vote to keep it calculated the way you have for now.

**Comment by benloh** [comment]
Yeah, we'd have to reconcile the two cases.  More than likely we would just recalculate on import.  But is it useful at all to be able to export and view the size parameter?

**Comment by netcreateorg** [comment]
Not for me, but let's wait on Kalani to confirm she also doesn't need it.

**Comment by benloh** [comment]
Size and weight implemented with #217.
* `weight` is used as a parameter to calculate `size` (sum of weights = size)
* `weight` has no UI and is not saved currently, but it defaults to 1.
