### ISSUE TITLE
Bad import traps you

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#229]
Steps to reproduce:

1. Go to export and save out nodes table
2. Go to import and try and import it as edges, causes an obvious error
3. Try re-importing as nodes, and nothing changes, and no cancel button
4. Reload page and you are locked out

Ideally, you can cancel and somehow recover from a failed import attempt but I don't see one.

**Comment by benloh** [comment]
@jdanish I wasn't able to reproduce this.  Can you send me the db file and template you're experiencing this with?  I specifically put in a few fixes to address this.

Also, when you are locked out, theoretically if you navigate away (e.g. close the More panel, or re-open the template panel, the locking should be reset).

**Comment by jdanish** [comment]
Uploaded to https://github.com/netcreateorg/netcreate-2018/issues/230

**Comment by jdanish** [comment]
I think this is no-longer an issue once I tried npm ci and then ran again.

**Comment by jdanish** [comment]
Sorry, closing.
