### ISSUE TITLE
Edges table edit button works even when not logged in

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#231]
Ideally, the edit button in the nodes and edges tables would either not appear or just read "show" or similar when logged out. But currently the nodes edit button works as desired (shows the node, but doesn't allow editing) whereas the edges edit button does allow editing. So if it is faster, just disabling editing would work with a longer-term goal of hiding or changing the text on the buttons.

**Comment by benloh** [comment]
Good catch!  Should be fixed now with referenced commits above.

**Comment by benloh** [comment]
@jdanish Please close if fixed.

**Comment by jdanish** [comment]
Fixed!! Thanks!

**Comment by jdanish** [comment]
Sorry @benloh  one minor thing just noticed - if you click view on edge table it opens the node but not the specific edge. If it's a quick fix, cool. If it's a hassle, it can wait for future rounds.

**Comment by benloh** [comment]
Gah.  The non-logged in locking was preventing it from opening when edit was requested.  Should be fixed now.

**Comment by jdanish** [comment]
Seems the opposite - it no-longer opens on edit or view?

**Comment by benloh** [comment]
Crikey.  What does the console say?  You should see a warning "EdgeEditor.EDGE_EDIT denied because isLocked true but we will gladly show it".

**Comment by jdanish** [comment]
<img width="347" alt="Screen Shot 2022-03-24 at 3 22 39 PM" src="https://user-images.githubusercontent.com/5529898/159994434-e2478d96-23e4-42b8-a07c-f5344f22db00.png">

**Comment by benloh** [comment]
Sorry, missed a line when committing because it had inadvertently gotten pushed behind a debug log.  Try again please?

**Comment by jdanish** [comment]
All fixed! Thanks!
