### ISSUE TITLE
Delete node causes error

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#235]
To reproduce, open a network, select a node, click delete (happens with and without merging). There appears to be no change. Check the console and see the error below. Reload and change becomes visible. Note that other viewers don't see a change unless they reload as well.

![Screen Shot 2022-03-30 at 5 57 51 PM](https://user-images.githubusercontent.com/5529898/160938083-7c55971a-7411-4598-b21e-4749d81dbb1e.png)

**Comment by benloh** [comment]
Good catch!  Fixing now.

**Comment by jdanish** [comment]
Sorry for the typo in the name.

----
(from my iPhone)

Joshua Danish
http://www.joshuadanish.com

**Comment by benloh** [comment]
@jdanish I believe 93bc8539df6259d4d13a7fb4db4fb57474d9dcc6 should fix this.  Just pushed.

This was a side effect of our separating the core "raw" data from the "working" filtered data that was necessary to get import/export working.  We ended up with a few straggling references to the deprecated data format.  I *think* all the old references are now chased down as well.

**Comment by jdanish** [comment]
Looks good thanks!
