### ISSUE TITLE
Commenting first pass for VFOI

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#243]
Goal: to pilot the inclusion of comments in the system
Implementation:

- [x] Add an optional, additional text box to the **node and edge** properties called comment, that has expanded space for text like the current notes field. 
- [x] Set this text box apart visually as the last attribute, and make it yellow so that it evokes a sticky note / comment
- [x] Include comments in filters (as a text string)
- [x] Add to table views as a column
- [ ] Optional but nice - collapse inside the table view if it is more than X lines of text where X is something we can negotiate / set.
- [ ] Make backwards compatible in templates (e.g., either ignore the comments if it is not in the template, or add it to the template if it is not there, and set to hidden by default).

Note: While we'd ultimately like replies, names, and time-stamps, these will require the new DB so we'll include them as conventions for now.

**Comment by benloh** [comment]
@jdanish One clarification here: Are multiple people adding comments to a single comment field?  Or does each person get to add a new comment field?

**Comment by jdanish** [comment]
For this pilot the edits are all in one comment field.
So it’s a bit of a kludge but let’s us try this out.
For the full implementation we want something more like meme with separate comments.

**Comment by jdanish** [comment]
<img width="379" alt="Screenshot 2023-05-25 at 9 17 49 AM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/2a3ffd33-b6d7-40a4-9aa9-1cc6608117c5">

Here is an example. Ignore the comments field since it is too small, but imagine the notes field is the comments field. I just typed in the conversation with dates. The convention is required since there is nothing to stop my from changing what Kalani says, but we will hope kids behave and have logs in case they don't.

**Comment by benloh** [comment]
Fields added in 6ad7b85746be6cf0cfd87a3fa9498d0442f0dc5c
