### ISSUE TITLE
Provenance first pass for VFOI

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#244]
This is a first pass at an integrated provenance intended for the Spring pilot. The goal is to test out the basics without having to revise the DB and overarching architecture.

- [x] Add a text field to all nodes and edges called Source (though make this something we can change, ideally). This should be a text field that can hold multiple lines.
- [x] If a node is created in the editor, set this text field initially to be something like "Added by TOKENID on DATE" with the user id and date inserted automatically. This will serve the primary use-case of kids editing fields. We (the admins / teachers) can then edit and replace these as needed to be things like "Imported from web on ... " or whatever. Long-term, we will want to track creation and revision automatically, get import info during imports and hand entered info in a similar format. But, for now, setting the initial info would be great.
- [x] Allow filtering to find the name of the source (basic string matching is fine). Long-term it'll be nice to filter separately for source of edits / insertions or for the date of insertion, but for now let's assume the source is fine.
- [x] Make this backwards compatible in the sense that either ignore the absence of the field in the template, or add an invisible entry to bring the database up to speed.

**Comment by benloh** [comment]
See 6ad7b85746be6cf0cfd87a3fa9498d0442f0dc5c

**Comment by benloh** [comment]
@jdanish We can't use "Source" as the label for Provenance on edges  because "Source" and "Target" are used for linking to source and target nodes on edges.  What do you want to call it?

**Comment by benloh** [comment]
# Graceful Conversion 

* [ ] * [ ] If `provenance` is not defined by the template (nodeDefs), should we...
   * [ ] add it to the template?  (update the template to include it?  add an entry, but default to `hidden`?)
   * [ ] default to hiding the field?
   * [ ] add it to the db file?

**Comment by jdanish** [comment]
Let’s go with origin for now. Thanks!----(from my iPhone)Joshua Danishhttp://www.joshuadanish.comOn May 25, 2023, at 5:38 PM, benloh ***@***.***> wrote:﻿
Graceful Conversion

 * [ ] If provenance is not defined by the template (nodeDefs), should we...

 add it to the template?  (update the template to include it?  add an entry, but default to hidden?)
 default to hiding the field?
 add it to the db file?

**Comment by jdanish** [comment]
Let’s go with provenance for now.
It’s technical but distinct.
