### ISSUE TITLE
Ensure sorting and filtering of numbers treats them as numbers

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#247]
There were some cases where these used string-based sorting, not numbers.

**Comment by jdanish** [comment]
This was reported by @kalanicraig so I am tagging her to maybe id the places?

**Comment by kalanicraig** [comment]
If you have an attribute in the edges table that's flagged as a number field, you'll see that you can filter on the edge weight for "> 5" and the filter will see "6" as > 5 but 46 as not > 5 .
