### ISSUE TITLE
Filter first pass at remove tab for VFOI

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#248]
Currently the filtering functionality has an option to highlight (fade) or filter, which hides the items not selected, but doesn't change their impact on the system. It'd be nice to have an additional "remove" tab that removes the impact of the filtered items on the system (e.g., don't impact centrality). Note that this should only be on the local display copy, so it will not impact the stored data.

**Comment by benloh** [comment]
Working on this will be a good way to get our heads around the filtering system and current data/state management.  So prioritizing it in front of the others.

**Comment by jdanish** [comment]
I wonder if we should change the top-level label to "Views" or something like that so that filter, highlight, remove and then eventually highlight or decorate or whatever all fit?  Not a high priority but related.

**Comment by benloh** [comment]
@jdanish how should the filtering search work for "remove/collapse"?  Are we **removing** everything that matches?  Or are we **keeping** everything that matches?

e.g. if I set a Collapse filter for nodes: <Type><contains><Person>, should we remove all the "Person" nodes, or should we remove all the non-person nodes?

**Comment by jdanish** [comment]
I think keep is most intuitive and matches the others.

**Comment by benloh** [comment]
Addressed.  Close for now.  See pull request #264
