### ISSUE TITLE
Issue with sorting provenance and comments when some are blank

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#261]
It looked like when every node / edge had content, the sorting worked OK on provenance and comment. However, when they are sparse, it appears to not work. I'd expect that if there are only a few, sorts will put those on the top / bottom, alphabetically. But they are floating in the middle. 

<img width="1156" alt="Screenshot 2023-05-29 at 2 17 41 PM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/05a3028c-42c6-4bb7-96ce-9b9b5314eec6">

**Comment by benloh** [comment]
Should already be fixed.
