### ISSUE TITLE
Rename Filter functions

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#263]
The current naming is confusing:
* "Filter" is a tab on the "Filter" panel?
* Does "Filter" remove or hide those that match?  Or does it hide those that don't match?  In other words are we filtering out the matches or is the filter keeping the matches?
* The only difference between "Highlight" and "Filter" is that "Filter" essentially sets transparency to 0?
* Should the name match the action that is applied to the matched items, or the action that is applied to the non-matched items?  Right now "Highlight" applies to the matched items, but "Filter" and "Collapse" to the unmatched.  

We really should come up with better more understandable function names for the three selections.

Challenges:
* The match action should be the same across the three tabs, e.g. you should be able to click back and forth between the three and the behavior of the matched and unmatched nodes/edges should be similar, going from fading to hiding to removing.

#### One idea: Function applies to the non-matched items...
1. "Fade" -- aka "Highlight" -- Keeps matched items, fades all unmatched items.
2. "Hide" -- aka "Filter" -- Keeps matched items, hides all unmatched items (but keeps all relationships intact)
3. "Remove" -- aka "Collapse" -- Keeps matched items, removes all unmatched items and recalculates all relationships

Any other ideas?  Are there other terms of art?

# TO DO
* [X] Rename panel from "FILTER" to "VIEWS" (or "REFINE VIZ")
* [x] Rename "Highlight" to "Fade"
* [x] Remove "Filter" function?
* [x] Rename "Collapse" to "Remove"

**Comment by benloh** [comment]
@jdanish @kalanicraig care to chime in?  You might also want to try out #264 first to see what it feels like.

**Comment by jdanish** [comment]
I'll let @kalanicraig note the state of the art, but for me:

1) For all 3, I agree with the implementation that the "matches" are kept, and the non-matches are "diminished" (faded in filter, hidden in filter, removed in collapse)

2) I agree on the naming issue and I think pitched somewhere that we rename the top-level to something like "View" or "Display" and include future decoration within it (e.g., changing color of what is highlighted).

3) I like fade, hide, and remove. Though it makes me think this should eventually be a template thing because that is intuitive for kids, but experts may require filter, etc?  (@kalanicraig )

**Comment by kalanicraig** [comment]
Filter should be the tab name, and fade/hide/remove is best. Collapse
usually means “take a bimodal network and collapse it to a unimodal
network” which is a whole set of data changes we don’t want to do yet.

**Comment by kalanicraig** [comment]
Joshua points out that “filter” doesn’t address node/edge re-visualization.
I’d pitch “Refine” or “refine viz” or something like that.

**Comment by benloh** [comment]
@jdanish @kalanicraig Sorry, another clarification: Is it correct to assume that you still want all three functions: fade, hide, and remove? e.g. that there is a functional difference between hiding and removing and that someones you'd want one view over the other depending on your purpose?

**Comment by jdanish** [comment]
I think yes. Technically we could do fade and just set the percentages to 0, so I'd be OK simplifying, but if it isn't an additional burden I'd leave them for now and see what folks think.

**Comment by benloh** [comment]
> I think yes. Technically we could do fade and just set the percentages to 0, so I'd be OK simplifying, but if it isn't an additional burden I'd leave them for now and see what folks think.

Actually it would be simpler if we removed the "2. Hide -- formerly-known-as'Filter'", because of #269 -- We need to differentiate how nodes are handled when they are removed from the Node Table vs how they are handled in the graph.  Keeping all three requires us to handle the views in three not-so-easily-teased-apart ways.  

It's probably the difference between 1 hour and 4 hours of work.  1hr to fix #269 if we drop Hide, 4hrs if we keep all three.

**Comment by jdanish** [comment]
From my standpoint for pedagogical purposes, Fade and Collapse do all the work we need. So I'd say drop "hide."

@kalanicraig can you verify it's not an issue from a DH perspective?
