### ISSUE TITLE
Collapse seems to disconnect matched nodes?

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#267]
<img width="1455" alt="Screenshot 2023-05-30 at 6 38 34 AM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/0a202a11-5d13-4b6e-ad34-7ecb6a18b9e4">
<img width="1446" alt="Screenshot 2023-05-30 at 6 38 52 AM" src="https://github.com/netcreateorg/netcreate-2018/assets/5529898/30438b04-1360-449e-9aa3-0e03437c4086">

Here is a before and after. I'd assume one and two would remain connected?

**Comment by benloh** [comment]
Weird.  I'm not seeing this behavior -- edges are not removed for me.  Can you upload the database and template you're using?

**Comment by jdanish** [comment]
Here you go. Note that the other networks we tend to have node type a connect to node type b, so if you hide node type b they will all go to 0 degrees, but here I tried to connect node type a to a and b, and that is where the problem became obvious. 

[Archive.zip](https://github.com/netcreateorg/netcreate-2018/files/11604309/Archive.zip)

**Comment by benloh** [comment]
Typo was removing edges based on `edge.id` instead of `target.id`.  Should be fixed by [f9c7f11].

**Comment by benloh** [comment]
@jdanish please test, confirm, and close.

**Comment by jdanish** [comment]
Looks good!
