### ISSUE TITLE
Collapse reduces degrees to 1

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#268]
Joshua reports:

One bug / error: it appears that collapses always reduces node degrees to 1 and then they do not re-set. For example, pick nodes that contain J:

Highlight works, all other nodes fade but size acts as if they are there
Filter works, all other nodes disappear but size acts as if they are there
Collapse removes all else, size fall to 1
Highlight again shows the correct things, but nodes remain small

**Comment by benloh** [comment]
@jdanish I'm not seeing this.  Can you tell me how to recreate?

Here's what I did:

1. Open ItestTeam.loki
2. Open Nodes Table
3. Scroll table to view "Joshua Danish".  Degrees = 28.
4. Open Filter (Highlight selected by default)
5. Select Node Filters > Name > contains.  Degrees = 28.
6. Type "j" in the contains field.  Degrees = 28.
7. Select the "Filter" filter.  All nodes but Joshua and Merijke are hidden.  Degrees = 28.
8. Select the "Collapse" filter.  All nodes but Joshua and Merijke are removed.  Degrees are recalculated to 0.  Joshua node size is small.


One thing worth noting is that the Collapse algorithm currently only recalculates the degrees for the matched nodes.  It ignores all the unmatched.

There does seem to be a bug where the Nodes Table is still showing the removed nodes (with their old degree values).

**Comment by jdanish** [comment]
I think I uploaded elsewhere, but the issue is tied to node that are connected to each other and also selected in the filter. Try collapsing to only people in this one? 

One is connected to Two and to Group, so collapsing should remove Group but leave One and Two connected with degrees 1, but they both go to 0.

[Archive.zip](https://github.com/netcreateorg/netcreate-2018/files/11604458/Archive.zip)

**Comment by benloh** [comment]
This should be fixed by f9c7f11f020d4b739196a6f8890cbda227851178
@jdanish please test and close.

**Comment by jdanish** [comment]
Collapsing seems to work, and clearing seems to work, but moving from filter - collapse - filter does not work because it is not re-set on the return to filter. Otherwise, looking good!

**Comment by benloh** [comment]
Yep.  #270 is addressing it.

**Comment by benloh** [comment]
Closing this issue.  Remaining issue is addressed by #270.
