### ISSUE TITLE
Should Collapse remove nodes from Nodes Table?

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#269]
Currently, when you Highlight or Filter a node, the faded and hidden nodes are still displayed in the Nodes Table formatted as transparent text or red text, respectively.

Collapse is using the same method as Filter: any removed nodes remain in the table with red text.

There are two potential issues:
* The removed nodes' degrees are not recalculated so they reflect old values -- this is because they have been removed from the active display list and the degree recalculation is only performed on the active display list.
* Should the Nodes Table reflect the fact that nodes have been removed and not merely hidden?  e.g. should the nodes disappear altogether from the table?

@jdanish please comment.

**Comment by jdanish** [comment]
I'd say yes, remove them unless there is a reason not to. I agree with all the confusion it may cause not to.

**Comment by benloh** [comment]
Addressed by e4fbfd6f0926e51eca1281d11bd06071e798763b and f411ba17e1dcb36be2c7b4bbd098449c3649ba49
