### ISSUE TITLE
"Clear Filters" needs to recalculate degrees

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#270]

**Comment by jdanish** [comment]
Note that moving between collapse and filter / highlight should also clear and re-set degrees otherwise the degrees change if you go:

filter -> collapse

but then stay too low when you revert

collapse -> filter

**Comment by benloh** [comment]
Yeah it's not being recalculated at all.  But I also need to fix the node table display too.  So all three issues are interrelated.

**Comment by benloh** [comment]
Addressed in 0bd8e975f8c7d8e8cc673cca468a45d3315cccb6
