### ISSUE TITLE
Change filter tab name from Collapse to Reduce and parameterize?

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#276]
Thanks for getting this working.

Kalani notes that Collapse is a technical term that is about reducing modality, so we can't use that. We think reduce (also technical) works, but we may want to change it in contexts for experts v/ kids so if that could go into the template also, that'd be great.

**Comment by benloh** [comment]
Names have been changed.  But still need to add to template.

**Comment by benloh** [comment]
#### Implementation Notes

* We can parameterize the labels in the template.  But then we need a fallback if we encounter a template that does not have the labels.
