### ISSUE TITLE
Make filter panel scroll if the screen isn't tall enough

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#277]
When the screen or window is too small, filters are not all visible. Can we make this panel scroll if hidden?

![Image](https://user-images.githubusercontent.com/5529898/243027615-25a49fe3-ef81-40d6-9e9e-6dd41a1635d0.png)

**Comment by benloh** [comment]
Fixed with ec603e7f08bad6881819237e329133d06e7296b7

**Comment by benloh** [comment]
@jdanish This should work now with the merged branches in `dev`.  Please verify and close.

**Comment by jdanish** [comment]
Verified!
