### ISSUE TITLE
Choose edge color based on highest edge weight

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#288]
If there are two edges between the same two nodes:

a -> b (green, weight 1)
a -> b (blue, weight 2)

Then display a->b as blue because it has a higher weight for that color. Note of course there might be more than one edge of that type. As in:

a -> b (green, weight 1)
a -> b (blue, weight 2)
a -> b (green, weight 1)
a -> b (green, weight 1)

The above should display green.

Otherwise, pick the first one in the edge list so that it is not random and is consistent.

**Comment by benloh** [comment]
I was actually in the middle of working on blending colors.  And blending is rather problematic too because you're probably going to get a lot of muddy colors.

Do you prefer this approach of taking the higher weight color?

**Comment by jdanish** [comment]
Let’s go with higher weight color thanks!! Mud won’t help anyone.

**Comment by benloh** [comment]
Implemented with df9977effed89375a061f8bad2c7561010c7ae31
