### ISSUE TITLE
Weight validation requires a 0 if delete

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-2018#289]
Currently if you delete the number to change it, it adds a 0 which is awkward because then you can't type a number.

**Comment by benloh** [comment]
Stupid react...I had just dealt with this with color validation.  I clearly need to make a generic validated number input component.

**Comment by benloh** [comment]
Implemented with 07b7a9f499cb9fa3540b8901719450d4986b5e7e
