### ISSUE TITLE
Review JSON Editor help text for form -- a lot of values are copied and pasted.

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#290]
The current `template-schema.js` has a lot of fields that were simply copied and pasted and descriptions, especially the property's main `description` field (e.g. `info.description`) and `help.description` field were copied from the original `node` object.

The default values should be reviewed, and then a new `_default.template.toml` file regenerated and checked into the repo.

**Comment by jdanish** [comment]
Is the best way to review this to open a new network and then just edit the template and read it all?  Or should I look somewhere else?

**Comment by benloh** [comment]
> Is the best way to review this to open a new network and then just edit the template and read it all? Or should I look somewhere else?

Yes that's probably the easiest way to catch errors.  But be sure to generate a new `_default.template.toml` first.  Actually let me do that now and check that in.

What's challenging in doing this is keeping clarity between the actual template data and the meta data that is needed for JSON Editor to do its magic.

**Comment by benloh** [comment]
@jdanish Please pull 61123f2d2642eb9444a45ab4cec2b93c38baa7ff and then create a new project and do the review.

**Comment by jdanish** [comment]
Got it. Is it easier for me to just make minor changes directly?  Or let you know what they are?

**Comment by benloh** [comment]
Your call.  If you can figure out how to do it, go ahead and make the changes.  That'll save budget.  But if you're concerned or confused, just let me know what to fix.

**Comment by jdanish** [comment]
Actually, it all looks good aside from changing the display label to Notes instead of Significance for nodes and edges then I can approve. Thanks!

**Comment by benloh** [comment]
Fixed with #291
